### ISSUE TITLE
Point Upstream Habitat layer at PSMFC endpoint [ V. Easy ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#103]
Brett should have already sent the endpoint(s) late last year.

**Comment by jtutak** [comment]
From Brett's 12/6 email: 

Just a reminder that we would also like to see the potential upstream habitat lines displayed in the results/report page, as well as the “Baseline Fish Habitat” layer.  
Ideally, the upstream reaches could be queried from this REST endpoint when looking at the results of an individual barrier: https://maps.psmfc.org/server/rest/services/CFPF/CFPF_FISHPass/MapServer/3
And, the Baseline Fish Habitat layer would be a “background” layer which would turn on at an appropriate scale, then could be turned off through the layer list/TOC by a user.  Here is the REST endpoint of that service: https://maps.psmfc.org/server/rest/services/CFPF/CFPF_FISHPass/MapServer/2  Please let me know if you have any questions on these two layers/services.
