### ISSUE TITLE
(No. 17 B) Display Filter Parameters on report page and in CSV [ Medium ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#106]
Need to decide if these will just be tallied on their own or populated in the description to be edited by user if desired.

NOTE: Ryan suggests we include these explicitly, rather than figuring out how to aggregate this in description (what to do if user has already written custom description?)

**Comment by jtutak** [comment]
We're telling the client that they need to record the parameters in the description, but the tool is stalling when I try to include text with colons, semicolons, and commas, as well as with returns. If this is how the client will be tracking inputs, we need to offer a way to do it and make clear if there are restricted characters. 

Including a pic of what it looks like when I hit save with the above formatting:

![issues](https://user-images.githubusercontent.com/1626572/53262603-e6ad9380-368b-11e9-9953-81d47abadbe1.PNG)
