### ISSUE TITLE
Add visualization layers to tool [very easy]

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/FishPass#121]
Jocelyn to prep and style all data before handing over to Ryan.

**Comment by jtutak** [comment]
List with layer names as preferred is here: https://docs.google.com/spreadsheets/d/1jUGEHTAEy1Vr1uPcNhBuj41wtOixSJ6lCs6cZin2nEM/edit?usp=sharing

**Comment by jtutak** [comment]
If layer names in the Google spreadsheet are too long, let me know. They are written as desired for now. 

They are also listed in order of priority.

**Comment by rhodges** [comment]
Was able to add MapServer layers. Was not able to add FeatureServer layers as we have neither the cartography to apply, nor a way of handling the large number of features returned.

**Comment by jtutak** [comment]
I believe I found a MapServer layer of the PAD. See the Google Spreadsheet for updated links, which are highlighted in green.
