### ISSUE TITLE
Filters aren't all working (ownership?)

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#124]
* Click on HUC @ Stockton, CA. 
   * gives 26 results
* Filter out "unknown" ownership
   * gives 2 results
* Report
   * shows 12 results

**Comment by rhodges** [comment]
The 10 "new" barriers have "NA" for estimated cost - they are not fixable (I think).

**Comment by jtutak** [comment]
Issue related to card in MVP project. RH is working on it.

**Comment by rhodges** [comment]
This is a non-issue - the extra barriers presented in the report are a result of not excluding downstream barriers. If downstream barriers are included in the optimization, or even have impacts that are considered in optimization, then they will show up in the report as their data is relevant.
