### ISSUE TITLE
Legend issues

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/FishPass#147]
- Is there a downside to bumping the font down by a point or two? 

- Is there an easy way to indicate that the legend layers are clickable? An arrow next to each layer name, or a plus sign? Barring that: small-font words next to/under "Legend" -- something like "Click to expand"
  - or have them automatically opened (this may be too ugly)

**Comment by rhodges** [comment]
Dropping the font and space is no problem.
I'm attempting to add chevrons to indicate collapsibility, but that made me realize we still had a TON of external dependencies that needed to be brought in (so the tool doesn't suddenly stop working once a website stops hosting the specific version of a file we want).
Looking to do something like this: https://codepen.io/zabielski/pen/ZGLbav
