### ISSUE TITLE
Excluding individual barrier removes upstream barriers from consideration?

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/FishPass#149]
Note from Anne: 

"The other functionality issue appears to be with editing individual barriers and excluding them from the output. When I ran a San Juan HUC 10 run and excluded five barriers from the output, it removed thirteen barriers from the output. It appears to be both removing the five barriers and all of the upstream barriers which it should not be doing."

**Comment by jtutak** [comment]
From Anne: "This is a link to the project where I excluded 5 barriers from the output and it removed 13: http://fishpass.ecotrust.org/fishpass/get_report/fishpass_project_324/"

**Comment by rhodges** [comment]
She told the project not to fix barriers with 0 passability. Optipass has no interest in fixing barriers that fish can't reach at all.

I'm running some test cases to prove this and hitting some other errors (all barriers now have a post-pass of 0 in my dev environment - however that happened, I need to make sure it doesn't leave my computer)

**Comment by rhodges** [comment]
Problem sorted out with #157 . zero values will not persist in live environments.
