### ISSUE TITLE
Add info buttons to pop up menus

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/FishPass#152]
Is it possible to add info buttons similar to "Set Pre-Mitigation Passability" to the functions below? These would similarly be editable in the content management system you set up. 

1. The "Set Barrier Mitigation Costs" pop up? These would go next to the "Mitigation Cost" "Post-Passability" headers. 
2. The pop-up when you click on an individual barrier? These would go next to the PrePass, Cost
PostPass, Action

If you can get them set up, I can populate them with text.

**Comment by jtutak** [comment]
* [ ] Jocelyn will need to update the content management doc to match this.

**Comment by rhodges** [comment]
Oops, forgot @jtutak still had some tasks on this!

**Comment by jtutak** [comment]
The Barrier Edit pop up appears to have the same flat-block assigned to two info-button pop-ups. The "barrier-postpass-help-text" flat block is showing for both "Post-Pass" and "Action" info buttons, instead of "barrier-action-help-text" for "Action" as listed. This appears to be the case in the content management document image you shared (see pic below). 

If you can update the "Action" pop-up pull in the "barrier-action-help-text" I can update the content management doc with some image editing, unless that's easy for you. 

![image](https://user-images.githubusercontent.com/1626572/55363183-17ee6000-5491-11e9-8314-4658e9145a2b.png)
