### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#68]
* [x] Account (if logged in)
* [x] Login/Logout
* [ ] Link for required FlatPages
   * [ ] Contact
   * [ ] About
   * [x] (MORE?)* - with FlatPages Anne/ PacStates can create any additional pages they want. We should have a view that lists these
* [x] Launch App
* [x] Fix bugs preventing it from opening on click

**Comment by rhodges** [comment]
We could also dynamically add all FlatPages to hamburger menu. I didn't suggest this at first because I didn't want to have to add the correct context to EVERY view that loads a template.
This problem could be alleviated either by:
* [ ] creating a view called by all views that render a template to get the flatpage list context, or
* [ ] Using Ajax to query for the flatpage list and load them dynamically

Both of these seem harder than the solution above. This is worth discussing and exploring.

**Comment by rhodges** [comment]
All of the tricky FlatPage stuff is in #64

**Comment by pollardld** [comment]
static links for now

**Comment by rhodges** [comment]
Super Duper Easy: https://docs.djangoproject.com/en/1.11/ref/contrib/flatpages/#getting-a-list-of-flatpage-objects-in-your-templates
