### ISSUE TITLE
(No. 3) "Begin" Button not working on IE [ Easy ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#82]
Reported by Anne via feedback doc

**Comment by rhodges** [comment]
Update Beta Feedback Google Doc when Done.

**Comment by rhodges** [comment]
main.js uses tics for quotes - IE doesn't play with those.

**Comment by jtutak** [comment]
Note for Jocelyn: Open Layers 4 may not be supported by Internet Explorer. Ryan is working to identify a fix.

**Comment by jtutak** [comment]
Note for Jocelyn: Open Layers 4 may not be supported by Internet Explorer. Ryan is working to identify a fix.

**Comment by jtutak** [comment]
fixed as much as it can be.
