### ISSUE TITLE
(No. 4) Results Styling Issues [ Medium ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#83]
Name of tester: Brett Holycross
Affiliation: PSMFC
Email: bholycross@psmfc.org
The issue
On which step does the problem occur?  Results
Describe the issue:  
* The results need to better highlight the barriers selected in the optimization.  
* Having a long list of all the possible results and needing to click through each one to find the selected results (“Action = treat”) does not work well.  
* Additionally, the results map should highlight the selected barriers and there should be some interactive nature to the selected barrier and the map.  
* The “Total Cost” and “cost” field should be listed as “Total Estimated Coast” and “estimated cost”. 
* There is no need to show the coordinates in the web interface, since there is a map showing the location.
Browser name and version:NA
Insert screenshot (optional):
Additional information:
--

**Comment by jtutak** [comment]
Notes from 2/14 call with RH; these align with the bulleted requests, above. 
- no
- yes
- basically
- yes
- yes
