### ISSUE TITLE
(No. 9 A) Show/Hide Barrier Filter Layer [ Need More Info, Med. Hard? ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#86]
Anne does not want all layers to show on load. Ryan doesn't either, since they won't all load when full data is in place.

* Decide UI for WHEN to turn on barriers
* Decide logic for WHEN to turn on barriers
* Decide UI for WHERE to turn on barriers

**Comment by jtutak** [comment]
Note for Jocelyn: where in the workflow do you see barriers, and where not? Question for Anne, and Ryan should be part of that convo. 

Probably after location selection. 

Tied to performance tuning,
