### ISSUE TITLE
(No. 11) Help Text in Area Selection and Spatial Selection request [ Medium ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#87]
From Anne: 

* [x]  have a short explanation to users that they can select and/or deselect spatial locations by clicking on these areas in the map. 
   * [ ] Include an example of this in the explanation. 
* [x] (want) unselect all spatial selections instead of unselecting each watershed one by one.

The explanation in the pop-up for ‘Downstream Treatment’ in the excel version was pretty good. Was this explanation shortened for space reasons? 
If so, I suggest a slight revision, something like 
> “Should barriers downstream (i.e., of the areas you selected on the map) be considered as candidates for mitigation (i.e., repair or removal (‘adjustable’)), should downstream barriers be included for the purposes of calculating cumulative passability but otherwise excluded as candidates for mitigation (‘non-adjustable’), or should downstream barriers be completely ignored?” 

or if this sentence is too long try 

> “How should barriers downstream be treated in the analysis (i.e., barriers downstream of the areas you selected in the map)?
> * Adjustable: Considered as candidates for mitigation (i.e., repair or removal).
> * Non-adjustable: Be included for the purposes of calculating cumulative passability but otherwise excluded as candidates for mitigation.
> * Excluded: Be completely ignored.” 

In general, the pop-up explanations and text in the excel version are good and should be used in the new tool although some tweaking may be needed. Please let me know if you need any additional text, documentation or text for page content from us.

I also suggest 
* [ ] including some explanation that the “Focus Areas” in the list of layers are the areas highlighted on the map that the user chose.
* [x] Including some text to tell users they must make a spatial selection - that is, click on areas of the map to select their focus areas before clicking on ‘Next’ even if they want to run the analysis on all barriers.

**Comment by jtutak** [comment]
* [ ]  have a short explanation to users that they can select and/or deselect spatial locations by clicking on these areas in the map. 
   * [ ] Include an example of this in the explanation. 
Include this in text and content updates, include in delivery. 

* [ ] (want) unselect all spatial selections instead of unselecting each watershed one by one.
Don't do this before beta, specifically talk with testers to get feedback.
