### ISSUE TITLE
(No. 15 & 20) Info popup and more updates regarding budget vs. barrier count [ Easy ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#91]
See clarification and task breakdown from Jocelyn, in separate comment, at bottom. You can skip this comment from Anne unless you need more context. 
--
From Anne:

Since the budget box can take both the # of barriers to remove or the monetary budget for removing barriers, there should be a 

* [x] pop-up in the budget explaining what this box represents. 

That is, if “Use Est. Costs” is unchecked above, than place the # of barriers you want treated in the budget box; otherwise, place a dollar value for the budget you have to treat/remove barriers. Also 

* [x] either remove $ next to the budget or have it automatically removed/changed to # of barriers if “Use Est. Costs” is unchecked. This should also be made clear in the results page too.

**Comment by jtutak** [comment]
[ ] Jocelyn needs to translate this into clear direction for Ryan.

**Comment by jtutak** [comment]
Ryan:
* [ ] Remove "$" from budget box.

Jocelyn
* [ ] Update text or pop up with additional language to  make clear:
- If "Use Estimated Costs" is checked, enter a budget in USD in the Budget box below
- If "Use Estimated Costs" is unchecked, enter the number of barriers in the Budget box below

**Comment by rhodges** [comment]
I have modified the simplified tooltip text in @jtutak 's note above. This text comes from the forms.py file, so needed to be added by a developer. If we wish to include additional context, that can come from flatblocks.

**Comment by jtutak** [comment]
Awesome! Thanks for updating the tool tip and doing all the rest here. 

(Is this bad GitHub form, to just say thanks on a closed ticket?)

**Comment by jtutak** [comment]
I'm noticing that the "$" is still to left of "Budget" box, though you checked it off. Is that a bug, or is removing that entirely not possible?

**Comment by jtutak** [comment]
![image](https://user-images.githubusercontent.com/1626572/55003607-ef98ca00-4f95-11e9-8e40-f006400bf2ef.png)
