### ISSUE TITLE
(No. 17 A) More fields on CSV Export and on report page [ Medium ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#93]
From Feedback: 

* [x] The results and exports (csv’s) should also include the fields listed below (in this order and using these field names with the exception of the red text). However, the coordinates should be included in the exports (csv). If it is easier to include them in both the results page and csv export then please include them in both.
   * PAD ID
   * Action
   * Site Name
   * Site Type
   * Barrier Status
   * Stream Name
   * Tributary To
   * Watershed Name (just requires renaming Watershed to Watershed Name)
   * Watershed Level (i.e.,  HUC 8/Subbasin)
   * County
   * ESUs
   * Estimated Upstream Habitat
   * \# of Downstream Barriers
   * Downstream Barrier ID (corresponds to the PAD ID of the barrier downstream)
   * Average Upstream Reach Slope (as a %)
   * Average Upstream August Streamflow
   * Average Upstream Annual Streamflow
   * Upstream Mean Aug. Stream Temp. (aka NorWeST_Mean_S1_93_11)
   * Upstream Mean Weekly Max Aug. Stream Temp. (aka NorWeST_...M)
   * Estimated Cost
   * Road
   * Post Mile
   * Owner (name of the actual owner instead of ownership type).
   * Photo Hyperlink
   * BIOS Link

I like the changes to the results page. 

* [x] I suggest “Treated” to “To Treat” or make it clear that this is suggested treatment in page content here and this is just an imaginary run. 
   * I don’t want people to be confused that these sites have already been treated especially if they are used to working with the PAD which includes both barriers and those that have been treated. 
* [x] Include the “Description” in the results page below the title/header. 
 (... section moved into separate ticket #98 ...)
* [ ] Also include the # of barrier treated, total barriers, header/title of the run that was generated by the tool/user in the csv exports. 
   * The header/title will help users when they want to compare the exports saved on their computers with runs saved in the FishPASS tool. 
(... section moved to separate ticket #99 ...)
   * If “Individual Barriers” were listed in the bottom more like a spreadsheet (reading right to left instead of up-down, it might look better.

**Comment by rhodges** [comment]
NOTES & QUESTIONS:
   * PAD ID
   * Action
      * This will contain multiple columns for ranged runs.
   * Site Name
   * Site Type
   * Barrier Status
   * Stream Name
   * Tributary To
   * Watershed Name (just requires renaming Watershed to Watershed Name)
   * Watershed Level (i.e.,  HUC 8/Subbasin)
      * This is recorded for the project. **Do we want this for individual barriers as well?**
   * County
   * ESUs
   * Estimated Upstream Habitat
   * \# of Downstream Barriers
   * Downstream Barrier ID (corresponds to the PAD ID of the barrier downstream)
   * Average Upstream Reach Slope (as a %)
   * Average Upstream August Streamflow
   * Average Upstream Annual Streamflow
   * Upstream Mean Aug. Stream Temp. (aka NorWeST_Mean_S1_93_11)
   * Upstream Mean Weekly Max Aug. Stream Temp. (aka NorWeST_...M)
   * Estimated Cost
   * Road
   * Post Mile
   * Owner (name of the actual owner instead of ownership type).
   * Photo Hyperlink
   * BIOS Link

**Comment by rhodges** [comment]
Okay, ticket is mostly complete with the following caveats:
1 - I need to know which value we want for "Estimated Upstream Habitat":
   * Potential Habitat?
   * Upstream Miles?
2 - I CAN convert raw values for the avg upstream reach. However that requires consistency in the PAD values (they will always be a number between 0 and 1). Can I count on that, or should we just leave the raw value in for people to deduce for themselves?
3 - I am reporting Basin IDs in the "parameters" area. I am reporting Basin Names in the table. Do we only want IDs?

**Comment by jtutak** [comment]
* [ ] Jocelyn will email the client for answers.

**Comment by jtutak** [comment]
Questions:

If I pose question 2 verbatim to Brett and Anne, will they understand, or do I need to give them more context (admission: I do not know exactly to what you're referring)

On question 3, before I ask the client: where is the watershed level field coming from? Is that from the PAD, or from the user selection? (I get HUC08 when selecting by HUC08 and HUC12, and "Unknown" when selecting by ESU.) I have a feeling that the basin ID will be more useful, but I will ask the client since I'm sending other questions their way.

**Comment by rhodges** [comment]
Question 1 - add third option: "Both"
Question 2 - ( **skip it** - details below)
   * There is a field about upstream reach **slope** (I forgot to include that important word above).
   * Slope is represented as a %
   * Current values are often around 0.05 (which I'm assuming to be a 5% slope)
   * I can convert these, but if anyone uploads a "5" for 5% then everything goes real bad
   * **SKIP QUESTION 2** - I can just test if the value is greater than 1 and deal with it.
      * I'll even move the "%" into the column header so that the values will be numeric and can be sorted.

Question 3 - That error a new one on me. I have replicated the issue and am looking into it.
   * Still would be good to know if they want a readable watershed name anywhere or just ID fields.

**Comment by jtutak** [comment]
Thanks -- I'll add the "both" option and ask about watershed names/ID fields.

**Comment by rhodges** [comment]
Slope fix is in place for both staging and production.

**Comment by jtutak** [comment]
Brett says use HUC codes over names.

**Comment by jtutak** [comment]
Response from Brett:

"Please use the “Miles Upstream” field... I’m not sure where the other field “Potential Habitat” originates from."

**Comment by rhodges** [comment]
We will not get to adding # of barriers treated or considered to the CSV header. This is due partially to running out of time, partially to complexity of reporting these numbers for batch runs, and partially because CSVs now include Titles and optional descriptions for users to use to quickly identify what they are looking at.
