### ISSUE TITLE
(No. 17 C) PAD IDs in report map and layer style toggling [ Medium ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/FishPass#99]
Feedback, pulled from #93 \:
* [ ] Include PAD IDs in the pop-up within the map and allow users to turn on/off barriers to treat vs. not to treat in case someone wants to only see the solution in a print out of the solution.

**Comment by jtutak** [comment]
Can we break this up into:

- [ ] Include PAD ID in the pop-up in the map, and
- [ ] allow users to turn on/off barriers to treat vs. not to treat in case someone wants to only see the solution in a print out of the solution.

Seems like the former is a smaller task than the latter.

**Comment by jtutak** [comment]
2nd: addressed in overhaul of report page? 

Breaking up report by budget tics, easier and more performant, but lose single table and single map output.

**Comment by jtutak** [comment]
These have not been addressed as asked, but there are workarounds for both:

1. PAD IDs  can be pulled from table and from search box when clicked.
2. Can't turn off treat/don't treat, but can sort table, and there is a filtered CSV option.
